name: Required Labels

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]
jobs:
  enforce--ready-label:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 1
          labels: |
            ready to merge
          message: "Add the 'ready to merge' label to merge this PR"
  prevent-donotmerge-label:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 0
          labels: 'DO NOT MERGE'
          message: 'DO NOT MERGE label is not allowed on this PR'
