module.exports = function () {
  return {
    'free-solid-svg-icons': [
      'angles-down',
      'angles-up',
      'arrows-rotate',
      'at',
      'book',
      'bug',
      'caret-down',
      'caret-right',
      'check',
      'circle-check',
      'circle-info',
      'ear-listen',
      'flask',
      'globe',
      'pause',
      'play',
      'shield',
      'slash',
      'square-xmark',
      'square-up-right',
      'spinner',
      'toggle-off',
      'toggle-on',
    ],
    'free-brands-svg-icons': ['github'],
  };
};
